production:
  cloud_name: dgnchoz5g
  api_key: 934421652349555
  api_secret: qYotvO6pa3HkXn0Rz15Q4259kYs
  enhance_image_tag: true
  static_image_support: true
development:
  cloud_name: dgnchoz5g
  api_key: 934421652349555
  api_secret: qYotvO6pa3HkXn0Rz15Q4259kYs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dgnchoz5g
  api_key: 934421652349555
  api_secret: qYotvO6pa3HkXn0Rz15Q4259kYs
  enhance_image_tag: true
  static_image_support: true


